# Generated by Django 6.0.5 on 2026-08-07 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('building_name', models.CharField(max_length=255)),
                ('floor_name', models.CharField(max_length=255)),
                ('background_file', models.FileField(upload_to='backgrounds/')),
                ('background_type', models.CharField(max_length=50)),
                ('cleaned_background_file', models.FileField(blank=True, null=True, upload_to='backgrounds_cleaned/')),
                ('use_cleaned_background', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrokCleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('before_image_data', models.TextField(blank=True)),
                ('after_image_data', models.TextField(blank=True)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('generation_prompt', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grok_cleaning_jobs', to='evacuation_plans.evacuationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grok_cleaning_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCleaningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_method', models.CharField(choices=[('local', 'Local cleanup'), ('local_walls', 'Local walls cleanup'), ('grok', 'Grok empty-base cleanup'), ('manual_edit', 'Manual eraser edit')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('image_file', models.FileField(upload_to='backgrounds_cleaned/history/')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_history', to='evacuation_plans.evacuationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cleaning_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('rotation', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('anchor_x', models.FloatField(blank=True, null=True)),
                ('anchor_y', models.FloatField(blank=True, null=True)),
                ('leader_width', models.FloatField(default=2.0)),
                ('framed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='evacuation_plans.evacuationplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('line', 'Line'), ('rect', 'Rectangle'), ('circle', 'Circle')], max_length=16)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('rotation', models.FloatField(default=0.0)),
                ('stroke_width', models.FloatField(default=3.0)),
                ('color', models.CharField(default='#000000', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='evacuation_plans.evacuationplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlanText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('font_size', models.FloatField(default=24.0)),
                ('font_family', models.CharField(default='Arial', max_length=64)),
                ('color', models.CharField(default='#000000', max_length=16)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('background_color', models.CharField(blank=True, max_length=16, null=True)),
                ('rotation', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='evacuation_plans.evacuationplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserXaiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
