# Generated by Django 6.0.5 on 2026-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planshape',
            name='shape_type',
            field=models.CharField(choices=[('line', 'Line'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('zone', 'Zone')], max_length=16),
        ),
    ]
