# Generated by Django 6.0.5 on 2026-05-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationplan',
            name='cleaned_background_file',
            field=models.FileField(blank=True, null=True, upload_to='backgrounds_cleaned/'),
        ),
        migrations.AddField(
            model_name='evacuationplan',
            name='use_cleaned_background',
            field=models.BooleanField(default=False),
        ),
    ]
