# Generated by Django 6.0.5 on 2026-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0002_alter_planshape_shape_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planshape',
            name='points',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planshape',
            name='shape_type',
            field=models.CharField(
                choices=[
                    ('line', 'Line'),
                    ('rect', 'Rectangle'),
                    ('circle', 'Circle'),
                    ('zone', 'Zone'),
                    ('polygon_zone', 'Polygon zone'),
                ],
                max_length=16,
            ),
        ),
    ]
