# Generated by Django 6.0.5 on 2026-08-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0003_planshape_points_polygon_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='grokcleaningjob',
            name='target_background_color',
            field=models.CharField(default='#FFFFFF', max_length=32),
        ),
    ]
