# Generated by Django 6.0.5 on 2026-08-02 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0003_useropenaisettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIPlanCleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('loading_source', 'Loading source'), ('analyzing', 'Analyzing'), ('prompt_ready', 'Prompt ready'), ('generating', 'Generating'), ('saving_result', 'Saving result'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('before_image_data', models.TextField(blank=True)),
                ('after_image_data', models.TextField(blank=True)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('generation_prompt', models.TextField(blank=True)),
                ('models_used', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_cleaning_jobs', to='evacuation_plans.evacuationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_cleaning_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
