# Generated by Django 6.0.5 on 2026-08-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0004_grokcleaningjob_target_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='planshape',
            name='control_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='planshape',
            name='fill_color',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='planshape',
            name='fill_opacity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='planshape',
            name='tension',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planshape',
            name='color',
            field=models.CharField(default='#000000', max_length=32),
        ),
        migrations.AlterField(
            model_name='planshape',
            name='shape_type',
            field=models.CharField(choices=[('line', 'Line'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('zone', 'Zone'), ('polygon_zone', 'Polygon zone'), ('free_polygon_zone', 'Free polygon zone'), ('curve_polygon_zone', 'Curve polygon zone')], max_length=32),
        ),
    ]
