# Generated by Django 6.0.5 on 2026-08-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0005_planshape_control_points_planshape_fill_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grokcleaningjob',
            name='preset',
            field=models.CharField(default='evacuation', max_length=32),
        ),
        migrations.AlterField(
            model_name='plancleaninghistory',
            name='cleaning_method',
            field=models.CharField(choices=[('local', 'Local cleanup'), ('local_walls', 'Local walls cleanup'), ('grok', 'Grok empty-base cleanup'), ('grok_autocad', 'Grok AutoCAD cleanup'), ('manual_edit', 'Manual eraser edit')], max_length=64),
        ),
    ]
