# Generated by Django 6.0.5 on 2026-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0006_grokcleaningjob_preset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planicon',
            name='flip_x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planicon',
            name='flip_y',
            field=models.BooleanField(default=False),
        ),
    ]
