# Generated by Django 6.0.5 on 2026-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0007_planicon_flip_x_planicon_flip_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationplan',
            name='secondary_background_file',
            field=models.FileField(blank=True, null=True, upload_to='backgrounds_secondary/'),
        ),
    ]
