# Generated by Django 6.0.5 on 2026-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0007_openaiplancleaningjob_pricing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancleaninghistory',
            name='cleaning_method',
            field=models.CharField(choices=[('local', 'Local cleanup'), ('local_walls', 'Local walls cleanup'), ('openai_sketch_to_plan', 'OpenAI sketch to plan'), ('openai_existing_plan', 'OpenAI existing plan cleanup'), ('openai_applied', 'OpenAI applied result'), ('manual_edit', 'Manual eraser edit')], max_length=64),
        ),
    ]
