# Generated by Django 6.0.5 on 2026-08-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0008_alter_plancleaninghistory_cleaning_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('line', 'Line'), ('rect', 'Rectangle'), ('circle', 'Circle')], max_length=16)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('rotation', models.FloatField(default=0.0)),
                ('stroke_width', models.FloatField(default=3.0)),
                ('color', models.CharField(default='#000000', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='evacuation_plans.evacuationplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
