# Generated by Django 6.0.5 on 2026-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0009_planshape'),
    ]

    operations = [
        migrations.AddField(
            model_name='planicon',
            name='anchor_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planicon',
            name='anchor_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
