# Generated by Django 6.0.5 on 2026-08-05 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0010_planicon_anchor_x_planicon_anchor_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('font_size', models.FloatField(default=24.0)),
                ('font_family', models.CharField(default='Arial', max_length=64)),
                ('color', models.CharField(default='#000000', max_length=16)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('background_color', models.CharField(blank=True, max_length=16, null=True)),
                ('rotation', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='evacuation_plans.evacuationplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
