# Generated by Django 6.0.5 on 2026-08-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0011_plantext'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiplancleaningjob',
            name='cleanup_level',
            field=models.CharField(default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='openaiplancleaningjob',
            name='confirmed_plan_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='openaiplancleaningjob',
            name='detected_elements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='openaiplancleaningjob',
            name='detected_plan_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='openaiplancleaningjob',
            name='detection_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openaiplancleaningjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loading_source', 'Loading source'), ('detecting_type', 'Detecting plan type'), ('analyzing', 'Analyzing'), ('prompt_ready', 'Prompt ready'), ('generating', 'Generating'), ('saving_result', 'Saving result'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
