# Generated by Django 6.0.5 on 2026-08-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0012_openaiplancleaningjob_cleanup_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiplancleaningjob',
            name='cleaning_profile',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
