# Generated by Django 6.0.5 on 2026-08-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0018_editor_layer_visibility_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='planicon',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
