# Generated by Django 6.0.5 on 2026-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0026_defaulttemplateeditpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationplan',
            name='active_sheet_template_key',
            field=models.CharField(default='none', max_length=64, verbose_name='Template actif'),
        ),
        migrations.AddField(
            model_name='evacuationplan',
            name='active_sheet_template_name',
            field=models.CharField(default='Plan seul', max_length=255, verbose_name='Nom du template actif'),
        ),
        migrations.AddField(
            model_name='evacuationplan',
            name='active_sheet_template_version_id',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Version du template actif'),
        ),
    ]
