# Generated by Django 6.0.8 on 2026-09-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0041_autonomous_plan_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='planicon',
            name='leader_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
