# Generated by Django 6.0.8 on 2026-09-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0042_planicon_leader_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='planicon',
            name='leader_dot_size',
            field=models.FloatField(default=1.0),
        ),
    ]
