# Generated by Django 6.0.8 on 2026-09-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0043_planicon_leader_dot_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPictogramLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictogram_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['icon_type'],
                'constraints': [models.UniqueConstraint(fields=('user', 'icon_type'), name='unique_pictogram_label_per_user')],
            },
        ),
    ]
