# Generated by Django 6.0.8 on 2026-09-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_plans', '0044_userpictogramlabel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userpictogramlabel',
            name='unique_pictogram_label_per_user',
        ),
        migrations.AddField(
            model_name='userpictogramlabel',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictogram_labels', to='evacuation_plans.evacuationplan'),
        ),
        migrations.AddConstraint(
            model_name='userpictogramlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('plan__isnull', True)), fields=('user', 'icon_type'), name='unique_global_pictogram_label_per_user'),
        ),
        migrations.AddConstraint(
            model_name='userpictogramlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('plan__isnull', False)), fields=('user', 'plan', 'icon_type'), name='unique_plan_pictogram_label_per_user'),
        ),
    ]
